### ISSUE TITLE
Error: Cannot find module 'npm-yaml'

### ISSUE THREAD

**Issue by monolithed** [saschagehlich/npm-yaml#3]
```
➜ npm install -g npm-yaml
npm ERR! Error: Cannot find module 'npm-yaml'
npm ERR!     at Function.Module._resolveFilename (module.js:338:15)
npm ERR!     at Function.Module._load (module.js:280:25)
npm ERR!     at Module.require (module.js:364:17)
npm ERR!     at require (module.js:380:17)
npm ERR!     at cb (/usr/local/lib/node_modules/npm/lib/npm.js:257:7)
npm ERR!     at LOOP (/usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:7:26)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/slide/lib/chain.js:18:7
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm-yaml"
npm ERR! cwd /usr/local/www/
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! code MODULE_NOT_FOUND
npm http GET https://registry.npmjs.org/npm-yaml
npm http 304 https://registry.npmjs.org/npm-yaml
npm http GET https://registry.npmjs.org/json2yaml
npm http GET https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/json2yaml
npm http 304 https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/remedial
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/remedial
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/underscore
npm-yaml@0.0.1 /usr/local/lib/node_modules/npm-yaml
├── json2yaml@1.0.3 (remedial@1.0.7)
└── js-yaml@3.0.2 (esprima@1.0.4, argparse@0.1.15)
npm ERR! Error: Callback called more than once.
npm ERR!     at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:80:16)
npm ERR!     at save (/usr/local/lib/node_modules/npm/lib/install.js:329:12)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install.js:98:7
npm ERR!     at /usr/local/lib/node_modules/npm/lib/install.js:188:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:119:5
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR!     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:48:11)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:233:14
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "npm-yaml"
npm ERR! cwd /usr/local/www/
npm ERR! node -v v0.10.20
npm ERR! npm -v 1.3.11
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/www/npm-debug.log
npm ERR! not ok code 0
```

**Comment by SgtPooki** [comment]
Not able to reproduce on the latest version of node and npm. What are you running?

**Comment by monolithed** [comment]
It was 3 years ago, man 😄

**Comment by Enteleform** [comment]
I'm having a similar issue on `Windows 10.0.16299.371 Pro x64` with `npm 6.0.0` + `node 8.11.1` (*also tried `node 10.0.0`*).

However, it appears that @monolithed was unable to install `npm-yaml` at all; whereas I was able to install it, but am finding that the `onload-script` hook is not able to find `npm-yaml`.

[**Error Output @ Gist**](https://gist.github.com/Enteleform/cbae01474f827213ef3b45176b3fa386)
